live_config_reload = true

[shell]
program = "/bin/bash"

[font]
size = 20.0

[window]
decorations = "none"
blur = true
opacity = 0.9
padding = { x = 24, y = 24 }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true


# Built from the  Inferno theme
# Original: https//github.com/hafiz-muhammad/inferno-alacritty-theme

# Default colors
[colors.primary]
background = '#270d06'
foreground = '#d9d9d9'

# Normal colors
[colors.normal]
black   = '#330000'
red     = '#ff3300'
green   = '#ff6600'
yellow  = '#ff9900'
blue    = '#ffcc00'
magenta = '#ff6600'
cyan    = '#ff9900'
white   = '#d9d9d9'

# Bright colors
[colors.bright]
black   = '#663300'
red     = '#ff6633'
green   = '#ff9966'
yellow  = '#ffcc99'
blue    = '#ffcc33'
magenta = '#ff9966'
cyan    = '#ffcc99'
white   = '#d9d9d9'
